name = "kierstenly-project"
type = "webpack"
account_id = ""  # Your Cloudflare account ID
workers_dev = true
route = "kierstenly.dev/*"
zone_id = ""  # Your zone ID

[site]
bucket = "."  # Serve files from the root of your repository
entry-point = "workers-site"
