name = "kierstenly-project"
type = "webpack"
account_id = "4df2afa5ef1071646d18a40061b37c27"  # Your Cloudflare account ID
workers_dev = true
route = "kierstenly.dev/*"
zone_id = "c32bebbab0d00692a398ba2b7d6c99ac"  # Your zone ID

[site]
bucket = "./public"  # Or your build output directory
entry-point = "workers-site"
