name = "kierstenly-project"
type = "webpack"
account_id = "4df2afa5ef1071646d18a40061b37c27"  # Replace with your actual Account ID
workers_dev = true
route = "kierstenly.dev/*"
zone_id = "yc32bebbab0d00692a398ba2b7d6c99ac"  # Replace with your actual Zone ID

[site]
bucket = "."  # Serve files from the root of your repository
entry-point = "workers-site"
